### ISSUE TITLE
linker error: undefined reference to `COLS'

### ISSUE THREAD

**Issue by peti** [judah/terminfo#16]
We're experiencing strange linker errors trying to package `hopenpgp-tools` in SUSE Linux. I'm citing from http://pastebin.com/V9Hc1e6A:

~~~
[  154s] /usr/lib64/ghc-7.10.3/wlppr_2eQCMP8HCd6AO3S2kxQCi3/libHSwl-pprint-terminfo-3.7.1.4-2eQCMP8HCd6AO3S2kxQCi3.a(PrettyPrint.o):(.text+0x165): undefined reference to `COLS'
[  154s] /usr/lib64/ghc-7.10.3/wlppr_2eQCMP8HCd6AO3S2kxQCi3/libHSwl-pprint-terminfo-3.7.1.4-2eQCMP8HCd6AO3S2kxQCi3.a(Curses.o):(.text+0x201): undefined reference to `COLS'
~~~

These error come from `wl-pprint-terminfo` which in turn is based on the `terminfo` library. We've packaged [version 0.4.0.2](https://build.opensuse.org/package/show/devel:languages:haskell:lts:6/ghc-terminfo), following the recommendations from Stackage LTS 6.x.

Now, I am at a loss to explain these errors and I'm wondering whether you might have in idea? How is it possible that `wl-pprint-terminfo` ends up with this invalid reference?

**Comment by peti** [comment]
Ping @ekmett, who is the maintainer of `wl-pprint-terminfo`. It's possible that the issue lies in that library after all, not in `terminfo` itself. https://github.com/ekmett/wl-pprint-terminfo/blob/master/src/System/Console/Terminfo/PrettyPrint/Curses.hs#L24-L25 makes me think that's likely, actually.

Is it possible that this code can't deal with a multi-threaded build of `ncurses`?

**Comment by judah** [comment]
Yeah, `wl-pprint-terminfo` is the package that's trying to link to `COLS`:
http://hackage.haskell.org/package/wl-pprint-terminfo-3.7.1.4/docs/src/System-Console-Terminfo-PrettyPrint-Curses.html

For reference, `terminfo` itself used to have a problem with SUSE due to the API changing for multithreaded ncurses:
https://github.com/judah/terminfo/issues/7
 
Maybe `wl-pprint-terminfo` could use ioctl to get the terminal size, similar to Haskeline?
https://github.com/judah/haskeline/blob/master/System/Console/Haskeline/Backend/Posix.hsc#L66

**Comment by peti** [comment]
I've reported this issue at https://github.com/ekmett/wl-pprint-terminfo/issues/9. Thanks for your help!
