### ISSUE TITLE
Some platforms might need -ltinfo

### ISSUE THREAD

**Issue by jtdaugherty** [judah/terminfo#17]
A user of my `brick` library (which uses `vty`, which uses `terminfo`) has reported this issue:

https://github.com/jtdaugherty/brick/issues/75

Doing a little digging, it appears that this might be a general problem with some platforms where `libncurses` isn't linked with `libtinfo`.  Although this report mentions a potential hotfix,

https://github.com/ponylang/ponyc/issues/252

I am wondering if it makes sense to just add `tinfo` to the linker step for the Haskell `terminfo` package.  Thoughts?

CC @Sireeni

**Comment by judah** [comment]
The `terminfo` package already specifies `-ltinfo` if it finds `libtinfo`:
https://github.com/judah/terminfo/blob/master/configure.ac#L42

Furthermore, the Haskell `terminfo` is usually distributed as part of GHC (since it's needed to build the compiler).  You can see in the referenced `error-brick.txt` that it doesn't build a new version of `terminfo`, so it's using the built-in one.

One way that error could happen is if there's a mismatch between the system on which GHC was built (which had `tinfo`) and the one where it's run (which doesn't).  Does that make sense?

**Comment by jtdaugherty** [comment]
Yeah, I think that makes sense. I don't know where the user got their GHC distribution, but it's definitely possible it was built on a machine that different a different linking environment than the one in which they ran the build (and apparently they're on a Gentoo variant, so that's at least consistent with other reports of this error). They've been happy with the Gentoo hotfix for this, so I'm not sure there's much else to be done on this ticket. Thank you!
