### ISSUE TITLE
Hackage doesn't have updated base upper bound

### ISSUE THREAD

**Issue by yutotakano** [judah/terminfo#40]
I was trying to install `brick`, but it told me `terminfo`'s constraint was <4.14. According to this repo, the commit to bump it up to <4.17 was done a few weeks ago, yet it doesn't seem to be updated on the [Hackage page](https://hackage.haskell.org/package/terminfo-0.4.1.4), hindering installs.

I'm not exactly sure of the process of updating Hackage's index, but would you take a look?

**Comment by endgame** [comment]
As a Hackage trustee, I have published a metadata revision against the latest release of this package. I suppose there's nothing else to do here since the bump has been merged into the repo; can you please close this issue?

Note also: you can request trustee metadata revisions at https://github.com/haskell-infra/hackage-trustees/issues ; I just happened to stumble upon this in my own work.
