### ISSUE TITLE
Is Windows supported?

### ISSUE THREAD

**Issue by Bodigrim** [judah/terminfo#46]
I'm having difficulties to build this package on Windows. Is it supported? Could README please give some instructions? E. g., which MSYS packages to install or what needs to be in PATH.

**Comment by Bodigrim** [comment]
@Noughtmare might you know the answer? I found https://github.com/jtdaugherty/vty/issues/219#issuecomment-1139945890 according to which you had some success in building `terminfo` on Windows?..

**Comment by noughtmare** [comment]
I know I succeeded once, but now I can't get terminfo's configure script to find my installed `ncurses` library. It's such a trivial thing that can be solved by providing the path in the right place, but I don't know where that right place is.

**Comment by noughtmare** [comment]
OK, I can compile it by first installing `mingw-w64-x86_64-ncurses` with pacman in the mingw64 shell. Then run these commands:

```
$Env:C_INCLUDE_PATH = "C:\ghcup\msys64\mingw64\include"
$Env:LIBRARY_PATH = "C:\ghcup\msys64\mingw64\lib
cabal build --extra-include-dirs="C:\ghcup\msys64\mingw64\include\ncursesw"
```

**Comment by Bodigrim** [comment]
@jtdaugherty how do you feel about adding these instructions to README?

**Comment by jtdaugherty** [comment]
@Bodigrim are you thinking they'd go in the README for `terminfo`?

**Comment by Bodigrim** [comment]
I think it would be helpful to have build instructions in `README`, yes, but you are the boss :)

**Comment by jtdaugherty** [comment]
Hm, I didn't realize I had any authority. :) I remember talking about *possibly* helping out with maintenance on this package a while back but that was as part of an exploration of whether its current maintainer wanted that. I also now find myself without as much time on my hands, so I don't think I'm in a position to contribute much. I'm sorry if that has led to confusion!

With that said, I have basically no experience doing Haskell development on Windows so I cannot tell whether the above steps ought to be repeated in the README as general advice, nor could I say what the generalization of those steps would be or what assumptions they make about the build environment, etc. And since I don't do Windows development (at all, but especially with Haskell), I'm not in a position to test (and thus support) documented Windows instructions. At best I could say "a user found this incantation helpful one time, use at your own risk" which I would personally hesitate to put in the README of a package that I wanted to support.

**Comment by Bodigrim** [comment]
Sorry, I probably misread https://github.com/judah/terminfo/issues/48#issuecomment-1320997752

**Comment by jtdaugherty** [comment]
Hah, yes, I was a little surprised he moved on that so quickly!

**Comment by jtdaugherty** [comment]
In the spirit of helpfulness, what if we updated the README with a pointer to this ticket and a statement that while Windows is not officially supported, this ticket might prove useful?

**Comment by noughtmare** [comment]
I also feel like my way of making this package work on Windows is not ideal.

As for how general these steps are, I think it should work for anyone who uses Windows with the x86_64 architecture, has installed Haskell with ghcup, and uses the default directories for both ghcup and msys2. Adapting it to other directories should be pretty straightforward, but it is unfortunate that the toolchain doesn't seem to automatically find these installed libraries and includes.

I think a link to this ticket in the README would be a good compromise.

**Comment by jtdaugherty** [comment]
Done!
